### ISSUE TITLE
Run vunit with "--no-color" option or support parsing colors 

### ISSUE THREAD

**Issue by Gzah92** [Bochlin/vunit-test-explorer#1]
Hi,

first of all: Thanks a lot for the extension, I already like it a lot!
Unfortunately it didn't work out of the box for me, and after looking into the code it was clear that it's due to the parsing not supporting the console color formatting VUnit outputs per default.
Adding the option "--no-color" makes it work, so it would be great if either this option would be added transparently or all terminal formatting would be ignored for the VUnit output parsing. 
Thanks again!

**Comment by Bochlin** [comment]
Glad that you appreciate the extension!

This works on my Windows machine, but I have not tested it properly on Linux. Are you running Linux?

It does however make sense to run with --no-color for robustness, the output tab of VSCode does not support coloring anyway as far as I know.

**Comment by Gzah92** [comment]
Yes, I was trying to run on Ubuntu 18.04. Thanks for accepting the pull request!
