### ISSUE TITLE
Change working directory to where "run.py" is located

### ISSUE THREAD

**Issue by Gzah92** [Bochlin/vunit-test-explorer#2]
Thanks again for the great extension!

Currently the working directory behavior is unexpected to me: With standalone VUnit it's set to the script location, while in the extension it's the workspace location. So if you expect the script location relative paths for the source files in "run.py" don't match up anymore.

While it can easily be fixed by using absolute paths in the script, I think a behavior identical to the standalone version would ease the integration.

**Comment by Bochlin** [comment]
I'm not sure that VUnit has any convention for the working directory, most of the examples make all paths relative to the directory of `run.py`  explicitly in the script e.g:
```
SRC_PATH = Path(__file__).parent / "src"
```

The output path defaults to a folder in the current working directory. I would agree though that the directory of the `run,py` files makes for a more sensible default. Adding a property to configure the working directory would make sense as well.

**Comment by Gzah92** [comment]
Today I showed a colleague the extension, and he had trouble getting it to run exactly because of this issue. I'll create a pull request for this tomorrow if it's fine with you.

**Comment by Bochlin** [comment]
That would be great.
