### ISSUE TITLE
Moving rows around messes with `Run|Debug|Show in Test Explorer` placement

### ISSUE THREAD

**Issue by halfow** [Bochlin/vunit-test-explorer#6]
Moving rows around messes up 
* the placement of `Run|Debug|Show in Test Explorer` 
* icons `pass/fail/not run` multiply while moving a row.

Minor issue, `Test Explorer: Reload Tests` makes it look right again.

A quick fix would be to make `Test Explorer: Reload Tests`  run on save. 

Was really easy to get going! nice work :)

**Comment by Bochlin** [comment]
The option `vunit.watch` can be enabled to watch the run.py file for changes.  
Most of the heavy lifting and annotations are done by the Test Explorer UI extension used by vunit-test-explorer.

**Comment by halfow** [comment]
Okay, then i agree that the problem/missing option probably relies within Test Explorer UI. I will research it some more
